### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by dustin2050** [daniell2-95/trading_with_ml#1]
Hello,

i tried to run this on Ubuntu LTS 22.04 and get the following Error when i try to access the frontend:

MissingSchema: Invalid URL 'xxxxxxxxxxxxxxxxxxxx/load': No scheme supplied. Perhaps you meant https://xxxxxxxxxxxxxxxxxxxx/load?

**Comment by daniell2-95** [comment]
Hello,

So the project was more for me to play around with technologies I haven't got the chance to work with at my job. Things like the server uri and credentials are not public as they will be a security breach to my AWS account. Let me know if you have any questions, and apologies for any inconvenience! 

Daniel
